### ISSUE TITLE
Incorrect power unit in README file

### ISSUE THREAD

**Issue by FrederikLauber** [aceisace/E-Paper-Calendar-with-iCal-sync-and-live-weather#15]
Hi,

the mainpage states:
"Altough mainly intended for the Raspberry Pi Zero W, mainly since it only requires 1W per hour, it works on the Rapsberry Pi 2/3 as well.".

My grievance is with the "1W per hour". Watt is already a measurement of energy per time making the statement physically nonsensical. It should either read "1W" or something like "1VAs per hour".

Also, (just noticing while writing) Altough is writen Although I think,
Cheers,
Frederik

**Comment by aceisace** [comment]
@FrederikLauber 
Hi Frederik. Thank you for pointing that out. I've changed the following:
`Altough mainly intended for the Raspberry Pi Zero W, mainly since it only requires 1W per hour`
with:
`Altough mainly intended for the Raspberry Pi Zero W, mainly since it requires very little power (1W)`
Does this sound correct now?

**Comment by FrederikLauber** [comment]
Sounds perfect! Thanks for changing it so quickly!

**Comment by aceisace** [comment]
You're welcome. Thanks for closing this issue.
